### ISSUE TITLE
Moo Fluids (moofluids) encountered an error during the complete event phase

### ISSUE THREAD

**Issue by Lynden-Sylvester** [Porting-Dead-Mods/Fluid-Cows#2]
MC 1.20.1

MoFluids-1.20.1-Neo(Forge)-1.0.2

Forge 47.3.0

Error:

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.m_135827_()" because the return value of "net.minecraftforge.registries.IForgeRegistry.getKey(Object)" is null.

Here's the latest.log:

[latest.log](https://github.com/user-attachments/files/15981076/latest.log)

Here's the crash log:

[crash-2024-06-27_15.32.44-fml.txt](https://github.com/user-attachments/files/16020322/crash-2024-06-27_15.32.44-fml.txt)

**Comment by Thepigcat76** [comment]
this should fix it https://github.com/Porting-Dead-Mods/Fluid-Cows/commit/ea8d3731aa628d13749af705306bf8b131c80598

**Comment by Thepigcat76** [comment]
oh sorry, wrong commit
