### ISSUE TITLE
Feature Request: Option to Disallow Gathering Milk From Fluid Cows

### ISSUE THREAD

**Issue by Darkosto** [Porting-Dead-Mods/Fluid-Cows#3]
Hello!

I have been enjoying the mod so far and getting it setup in my pack has been pretty simple! Is it possible to add in a config option to stop Fluid Cows from being milkable aside from their fluid resources? When setting up automation, it creates a potentially complex or bothersome situation to divert the milk into a trash can or other tank to deal with. 

Thank you very much for making this mod!
Darkosto

MC: 1.20.1
Neoforge: 47.1.106
Fluid Cows: 1.0.3

**Comment by Leclowndu93150** [comment]
Thank you for the report, the fix should be released today alongside the Jade support

**Comment by Leclowndu93150** [comment]
![image](https://github.com/Porting-Dead-Mods/Fluid-Cows/assets/73310949/608c75f2-2932-4cc6-b75f-a86787a410bc)
we're still today technicaly (for me)
