### ISSUE TITLE
Fluid Cows Spawn on pollition blocks from Pollution of the Realms

### ISSUE THREAD

**Issue by arketec** [Porting-Dead-Mods/Fluid-Cows#4]
Running this mod with the mod [Polution of the Realm](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realmsl), Fluid cows spawn on the pollution blocks generated by this mod, but since they have no hitbox, the cows just fall to their death from y =196, so there is a constant rain of falling, dying cows when running these mods together

**Comment by Leclowndu93150** [comment]
>  so there is a constant rain of falling, dying cows when running these mods together



AHHAHAHAHAH
